Repository prgrms-be-devcourse/NBE1_2_Team03, pull requests merged in 2024-10, with the labels that each got.

#21 Feature/15 delete board API
  src/main/java/com/sscanner/team/board/controller/BoardController.java
  src/main/java/com/sscanner/team/board/entity/Board.java
  src/main/java/com/sscanner/team/board/entity/BoardImg.java
  src/main/java/com/sscanner/team/board/service/BoardService.java
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.java
  src/main/java/com/sscanner/team/global/common/service/ImageServiceImpl.java
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
Labels: ✨ Feature, 훈일

#20 Feature/3 add product page api
  build.gradle
  src/main/java/com/sscanner/team/PaymentRecord.java
  src/main/java/com/sscanner/team/SScannerApplication.java
  src/main/java/com/sscanner/team/UserPoint.java
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/java/com/sscanner/team/points/common/PointConstants.java
  src/main/java/com/sscanner/team/points/common/PointManager.java
  src/main/java/com/sscanner/team/points/config/RedisConfig.java
  src/main/java/com/sscanner/team/points/controller/PointController.java
  src/main/java/com/sscanner/team/points/controller/RedisController.java
  src/main/java/com/sscanner/team/points/repository/PaymentRepository.java
  src/main/java/com/sscanner/team/points/repository/PointRepository.java
  src/main/java/com/sscanner/team/points/requestdto/PaymentRequestDto.java
  src/main/java/com/sscanner/team/points/requestdto/PointPaymentRequestDto.java
  src/main/java/com/sscanner/team/points/requestdto/PointRequestDto.java
  src/main/java/com/sscanner/team/points/requestdto/PointUpdateRequestDto.java
  src/main/java/com/sscanner/team/points/responsedto/PointResponseDto.java
  src/main/java/com/sscanner/team/points/scheduler/PointScheduler.java
  src/main/java/com/sscanner/team/points/service/PaymentService.java
  src/main/java/com/sscanner/team/points/service/PaymentServiceImpl.java
  src/main/java/com/sscanner/team/points/service/PointService.java
  src/main/java/com/sscanner/team/points/service/PointServiceImpl.java
  src/main/java/com/sscanner/team/products/controller/ProductController.java
  src/main/java/com/sscanner/team/products/repository/ProductRepository.java
  src/main/java/com/sscanner/team/products/responsedto/ProductResponseDto.java
  src/main/java/com/sscanner/team/products/service/ProductService.java
  src/main/java/com/sscanner/team/products/service/ProductServiceImpl.java
  src/main/java/com/sscanner/team/util/UUIDConverter.java
  src/main/resources/application.yml
Labels: ✨ Feature, 정원

#24 Feature/23 Board update API
  src/main/java/com/sscanner/team/board/controller/BoardController.java
  src/main/java/com/sscanner/team/board/entity/Board.java
  src/main/java/com/sscanner/team/board/entity/BoardImg.java
  src/main/java/com/sscanner/team/board/repository/BoardImgRepository.java
  src/main/java/com/sscanner/team/board/requestdto/BoardUpdateRequestDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardImgResponseDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardResponseDTO.java
  src/main/java/com/sscanner/team/board/service/BoardImgService.java
  src/main/java/com/sscanner/team/board/service/BoardImgServiceImpl.java
  src/main/java/com/sscanner/team/board/service/BoardService.java
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.java
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
Labels: ✨ Feature, 훈일

#28 Feature/25 ci 파이프라인 구축
  .github/workflows/ci.yml
Labels: ✨ Feature, 재희

#32 Feature/22 쓰레기통 이미지 등록, 조회 API 구현
  src/main/java/com/sscanner/team/global/common/service/ImageServiceImpl.java
  src/main/java/com/sscanner/team/global/configure/S3Config.java
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/java/com/sscanner/team/trashcan/controller/TrashcanApiController.java
  src/main/java/com/sscanner/team/trashcan/entity/TrashcanImg.java
  src/main/java/com/sscanner/team/trashcan/repository/TrashcanImgRepository.java
  src/main/java/com/sscanner/team/trashcan/responseDto/TrashcanWithImgResponseDto.java
  src/main/java/com/sscanner/team/trashcan/service/TrashcanImgService.java
  src/main/java/com/sscanner/team/trashcan/service/TrashcanImgServiceImpl.java
  src/main/java/com/sscanner/team/trashcan/service/TrashcanService.java
  src/main/java/com/sscanner/team/trashcan/service/TrashcanServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Feature, 서진

#31 Feature/26 read boards API
  src/main/java/com/sscanner/team/board/controller/BoardController.java
  src/main/java/com/sscanner/team/board/entity/Board.java
  src/main/java/com/sscanner/team/board/entity/BoardImg.java
  src/main/java/com/sscanner/team/board/repository/BoardRepository.java
  src/main/java/com/sscanner/team/board/responsedto/BoardImgResponseDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardListResponseDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardResponseDTO.java
  src/main/java/com/sscanner/team/board/service/BoardService.java
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.java
Labels: ✨ Feature, 훈일

#36 Feature/29 cd 파이프라인 구축
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  Dockerfile
  appspec.yml
  docker-compose/compose.blue.yml
  docker-compose/compose.green.yml
  scripts/start-server.sh
  src/main/java/com/sscanner/team/HealthController.java
Labels: ✨ Feature, 재희

#40 Feature/34 주변 쓰레기통 조회 API 구현
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/java/com/sscanner/team/global/utils/GeoUtils.java
  src/main/java/com/sscanner/team/trashcan/controller/TrashcanApiController.java
  src/main/java/com/sscanner/team/trashcan/repository/TrashcanRepository.java
  src/main/java/com/sscanner/team/trashcan/service/TrashcanService.java
  src/main/java/com/sscanner/team/trashcan/service/TrashcanServiceImpl.java
Labels: ✨ Feature, 서진

#46 Feature/42 ci 파이프라인에 sonarqube 도입
  .github/workflows/ci.yml
  build.gradle
Labels: ✨ Feature, 재희

#52 Feature/51 add userutils
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.java
  src/main/java/com/sscanner/team/global/utils/UserUtils.java
  src/main/java/com/sscanner/team/jwt/JWTFilter.java
  src/main/java/com/sscanner/team/jwt/LoginFilter.java
Labels: ✨ Feature, 지은

#59 chore: coolsms 환경변수 추가
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  docker-compose/compose.blue.yml
  docker-compose/compose.green.yml
Labels: 🔨 Refactor, 재희

#47 Feature/27 product img api
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/java/com/sscanner/team/payment/controller/PaymentController.java
  src/main/java/com/sscanner/team/payment/entity/PaymentRecord.java
  src/main/java/com/sscanner/team/payment/repository/PaymentRepository.java
  src/main/java/com/sscanner/team/payment/requestdto/PaymentRequestDto.java
  src/main/java/com/sscanner/team/payment/requestdto/PointPaymentRequestDto.java
  src/main/java/com/sscanner/team/payment/responsedto/PointPaymentResponseDto.java
  src/main/java/com/sscanner/team/payment/service/PaymentService.java
  src/main/java/com/sscanner/team/payment/service/PaymentServiceImpl.java
  src/main/java/com/sscanner/team/points/common/PointConstants.java
  src/main/java/com/sscanner/team/points/controller/PointController.java
  src/main/java/com/sscanner/team/points/controller/RedisController.java
  src/main/java/com/sscanner/team/points/entity/UserPoint.java
  src/main/java/com/sscanner/team/points/redis/PointRedisManager.java
  src/main/java/com/sscanner/team/points/redis/RedisDataInitializer.java
  src/main/java/com/sscanner/team/points/repository/PointRepository.java
  src/main/java/com/sscanner/team/points/requestdto/PointUpdateRequestDto.java
  src/main/java/com/sscanner/team/points/scheduler/PointScheduler.java
  src/main/java/com/sscanner/team/points/service/PaymentService.java
  src/main/java/com/sscanner/team/points/service/PaymentServiceImpl.java
  src/main/java/com/sscanner/team/points/service/PointService.java
  src/main/java/com/sscanner/team/points/service/PointServiceImpl.java
  src/main/java/com/sscanner/team/products/controller/ProductController.java
  src/main/java/com/sscanner/team/products/entity/Product.java
  src/main/java/com/sscanner/team/products/entity/ProductImg.java
  src/main/java/com/sscanner/team/products/entity/ProductQr.java
  src/main/java/com/sscanner/team/products/repository/ProductImgRepository.java
  src/main/java/com/sscanner/team/products/repository/ProductRepository.java
  src/main/java/com/sscanner/team/products/responsedto/ProductResponseDto.java
  src/main/java/com/sscanner/team/products/responsedto/ProductUploadImgResponseDto.java
  src/main/java/com/sscanner/team/products/responsedto/ProductWithImgResponseDto.java
  src/main/java/com/sscanner/team/products/service/ProductImgService.java
  src/main/java/com/sscanner/team/products/service/ProductImgServiceImpl.java
  src/main/java/com/sscanner/team/products/service/ProductService.java
  src/main/java/com/sscanner/team/products/service/ProductServiceImpl.java
Labels: ✨ Feature, 정원

#62 Feature/61 add gifticon
  build.gradle
  src/main/java/com/sscanner/team/barcode/controller/BarcodeController.java
  src/main/java/com/sscanner/team/barcode/entity/Barcode.java
  src/main/java/com/sscanner/team/barcode/repository/BarcodeRepository.java
  src/main/java/com/sscanner/team/barcode/responsedto/BarcodeResponseDto.java
  src/main/java/com/sscanner/team/barcode/service/BarcodeService.java
  src/main/java/com/sscanner/team/gifticon/controller/GifticonController.java
  src/main/java/com/sscanner/team/gifticon/responsedto/GifticonResponseDto.java
  src/main/java/com/sscanner/team/gifticon/service/GifticonService.java
  src/main/java/com/sscanner/team/global/common/service/ImageService.java
  src/main/java/com/sscanner/team/global/common/service/ImageServiceImpl.java
  src/main/java/com/sscanner/team/payment/entity/PaymentRecord.java
  src/main/java/com/sscanner/team/payment/requestdto/PaymentRequestDto.java
  src/main/java/com/sscanner/team/payment/service/PaymentServiceImpl.java
  src/main/java/com/sscanner/team/products/service/ProductImgService.java
  src/main/java/com/sscanner/team/products/service/ProductImgServiceImpl.java
Labels: ✨ Feature, 정원

#65 feat: ELK 환경변수 추가
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  docker-compose/compose.blue.yml
  docker-compose/compose.green.yml
Labels: ✨ Feature, 재희

#67 Feature/53 add user rud2
  src/main/java/com/sscanner/team/board/entity/Board.java
  src/main/java/com/sscanner/team/board/requestdto/BoardCreateRequestDTO.java
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.java
  src/main/java/com/sscanner/team/comment/entity/Comment.java
  src/main/java/com/sscanner/team/comment/requestdto/CommentCreateRequestDTO.java
  src/main/java/com/sscanner/team/comment/responsedto/CommentResponseDTO.java
  src/main/java/com/sscanner/team/comment/service/CommentServiceImpl.java
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/java/com/sscanner/team/global/utils/UserUtils.java
  src/main/java/com/sscanner/team/jwt/JWTFilter.java
  src/main/java/com/sscanner/team/jwt/JWTUtil.java
  src/main/java/com/sscanner/team/jwt/LoginFilter.java
  src/main/java/com/sscanner/team/payment/entity/PaymentRecord.java
  src/main/java/com/sscanner/team/payment/requestdto/PaymentRequestDto.java
  src/main/java/com/sscanner/team/payment/service/PaymentServiceImpl.java
  src/main/java/com/sscanner/team/points/entity/UserPoint.java
  src/main/java/com/sscanner/team/points/requestdto/PointUpdateRequestDto.java
  src/main/java/com/sscanner/team/user/controller/ReissueController.java
  src/main/java/com/sscanner/team/user/controller/UserController.java
  src/main/java/com/sscanner/team/user/entity/User.java
  src/main/java/com/sscanner/team/user/repository/UserRepository.java
  src/main/java/com/sscanner/team/user/requestdto/UserJoinRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserLoginRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserNicknameUpdateRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserPasswordChangeRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserPhoneUpdateRequestDto.java
  src/main/java/com/sscanner/team/user/responsedto/RefreshResponseDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserDetailsImpl.java
  src/main/java/com/sscanner/team/user/responsedto/UserJoinResponseDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserMypageResponseDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserNicknameUpdateResponseDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserPhoneUpdateResponseDto.java
  src/main/java/com/sscanner/team/user/scheduler/UserDeletionScheduler.java
  src/main/java/com/sscanner/team/user/service/CustomUserDetailsService.java
  src/main/java/com/sscanner/team/user/service/ReissueService.java
  src/main/java/com/sscanner/team/user/service/UserService.java
Labels: ✨ Feature, 지은

#60 Feature/55 add user sms
  build.gradle
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.java
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/java/com/sscanner/team/user/SmsCertificationUtil.java
  src/main/java/com/sscanner/team/user/controller/SmsController.java
  src/main/java/com/sscanner/team/user/repository/SmsRepository.java
  src/main/java/com/sscanner/team/user/repository/UserRepository.java
  src/main/java/com/sscanner/team/user/requestdto/SmsRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/SmsVerifyRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserJoinRequestDto.java
  src/main/java/com/sscanner/team/user/service/SmsService.java
  src/main/java/com/sscanner/team/user/service/UserService.java
  src/main/resources/application.yml
Labels: ✨ Feature, 지은

#70 feat : 핸드폰 번호 수정 시 문자 인증 추가
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/java/com/sscanner/team/user/controller/UserController.java
  src/main/java/com/sscanner/team/user/requestdto/UserPhoneUpdateRequestDto.java
  src/main/java/com/sscanner/team/user/service/UserService.java
Labels: ✨ Feature, 지은

#68 Refactor/63 product point payment
  src/main/java/com/sscanner/team/gifticon/responsedto/GifticonResponseDto.java
  src/main/java/com/sscanner/team/gifticon/service/GifticonService.java
  src/main/java/com/sscanner/team/payment/controller/PaymentController.java
  src/main/java/com/sscanner/team/payment/entity/PaymentRecord.java
  src/main/java/com/sscanner/team/payment/requestdto/PaymentRequestDto.java
  src/main/java/com/sscanner/team/payment/service/PaymentServiceImpl.java
  src/main/java/com/sscanner/team/points/common/PointConstants.java
  src/main/java/com/sscanner/team/points/controller/PointController.java
  src/main/java/com/sscanner/team/points/controller/RedisController.java
  src/main/java/com/sscanner/team/points/entity/UserPoint.java
  src/main/java/com/sscanner/team/points/redis/PointRedisManager.java
  src/main/java/com/sscanner/team/points/redis/PointRedisService.java
  src/main/java/com/sscanner/team/points/redis/PointRedisServiceImpl.java
  src/main/java/com/sscanner/team/points/redis/RedisDataInitializer.java
  src/main/java/com/sscanner/team/points/repository/PointRepository.java
  src/main/java/com/sscanner/team/points/requestdto/PointUpdateRequestDto.java
  src/main/java/com/sscanner/team/points/responsedto/PointResponseDto.java
  src/main/java/com/sscanner/team/points/responsedto/PointWithUserIdResponseDto.java
  src/main/java/com/sscanner/team/points/scheduler/PointScheduler.java
  src/main/java/com/sscanner/team/points/service/PointService.java
  src/main/java/com/sscanner/team/points/service/PointServiceImpl.java
  src/main/java/com/sscanner/team/products/controller/ProductController.java
  src/main/java/com/sscanner/team/products/entity/Product.java
  src/main/java/com/sscanner/team/products/entity/ProductImg.java
  src/main/java/com/sscanner/team/products/entity/ProductQr.java
  src/main/java/com/sscanner/team/products/responsedto/ProductImgResponseDto.java
  src/main/java/com/sscanner/team/products/responsedto/ProductResponseDto.java
  src/main/java/com/sscanner/team/products/responsedto/ProductUploadImgResponseDto.java
  src/main/java/com/sscanner/team/products/responsedto/ProductWithImgResponseDto.java
  src/main/java/com/sscanner/team/products/service/ProductImgService.java
  src/main/java/com/sscanner/team/products/service/ProductImgServiceImpl.java
  src/main/java/com/sscanner/team/products/service/ProductService.java
  src/main/java/com/sscanner/team/products/service/ProductServiceImpl.java
Labels: 🔨 Refactor, 정원

#72 Feture/71 아이디 비밀번호 찾기 추가
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.java
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/java/com/sscanner/team/user/controller/UserController.java
  src/main/java/com/sscanner/team/user/repository/UserRepository.java
  src/main/java/com/sscanner/team/user/requestdto/UserFindIdRequestDto.java
  src/main/java/com/sscanner/team/user/requestdto/UserResetPasswordRequestDto.java
  src/main/java/com/sscanner/team/user/responsedto/UserFindIdResponseDto.java
  src/main/java/com/sscanner/team/user/service/UserService.java
Labels: ✨ Feature, 지은

#78 Refactor/75 gifticon barcode
  src/main/java/com/sscanner/team/barcode/common/BarcodeConstants.java
  src/main/java/com/sscanner/team/barcode/controller/BarcodeController.java
  src/main/java/com/sscanner/team/barcode/responsedto/BarcodeResponseDto.java
  src/main/java/com/sscanner/team/barcode/service/BarcodeGenerator.java
  src/main/java/com/sscanner/team/barcode/service/BarcodeService.java
  src/main/java/com/sscanner/team/barcode/service/BarcodeServiceImpl.java
  src/main/java/com/sscanner/team/gifticon/service/GifticonService.java
  src/main/java/com/sscanner/team/products/service/ProductImgService.java
  src/main/java/com/sscanner/team/products/service/ProductImgServiceImpl.java
  src/main/java/com/sscanner/team/products/service/ProductService.java
  src/main/java/com/sscanner/team/products/service/ProductServiceImpl.java
Labels: 🔨 Refactor, 정원

#77 Feature/38 add admin
  src/main/java/com/sscanner/team/admin/controller/AdminController.java
  src/main/java/com/sscanner/team/admin/requestdto/AdminBoardRequestDTO.java
  src/main/java/com/sscanner/team/admin/responsedto/AdminBoardInfoResponseDTO.java
  src/main/java/com/sscanner/team/admin/responsedto/AdminBoardListResponseDTO.java
  src/main/java/com/sscanner/team/admin/responsedto/AdminEctBoardResponseDTO.java
  src/main/java/com/sscanner/team/admin/responsedto/AdminModifyBoardResponseDTO.java
  src/main/java/com/sscanner/team/admin/service/AdminService.java
  src/main/java/com/sscanner/team/admin/service/AdminServiceImpl.java
  src/main/java/com/sscanner/team/board/entity/Board.java
  src/main/java/com/sscanner/team/board/repository/BoardImgRepository.java
  src/main/java/com/sscanner/team/board/repository/BoardRepository.java
  src/main/java/com/sscanner/team/board/service/BoardImgService.java
  src/main/java/com/sscanner/team/board/service/BoardImgServiceImpl.java
  src/main/java/com/sscanner/team/board/service/BoardService.java
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.java
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.java
  src/main/java/com/sscanner/team/trashcan/entity/Trashcan.java
  src/main/java/com/sscanner/team/trashcan/entity/TrashcanImg.java
  src/main/java/com/sscanner/team/trashcan/service/TrashcanService.java
  src/main/java/com/sscanner/team/trashcan/service/TrashcanServiceImpl.java
Labels: ✨ Feature, 훈일

#83 feat: 웹 앱 환경 CORS 추가
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.java
Labels: ✨ Feature, 정원

#85 Feature/79 log monitoring plg
  docker-compose/compose.blue.yml
  docker-compose/compose.green.yml
  src/main/java/com/sscanner/team/global/configure/aop/HttpLoggingAspect.java
  src/main/java/com/sscanner/team/global/configure/aop/ServiceLogAspect.java
  src/main/java/com/sscanner/team/global/exception/GlobalExceptionHandler.java
  src/main/resources/logback-spring.xml
Labels: ✨ Feature, 재희
