Repository prgrms-be-devcourse/NBE1_2_Team03, pull requests merged in 2024-09, with the labels that each got.

#10 Feature/5 add user join
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/sscanner/team/User.java
  src/main/java/com/sscanner/team/config/SecurityConfig.java
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/java/com/sscanner/team/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sscanner/team/user/controller/UserController.java
  src/main/java/com/sscanner/team/user/repository/UserRepository.java
  src/main/java/com/sscanner/team/user/requestDto/UserJoinRequestDto.java
  src/main/java/com/sscanner/team/user/responseDto/UserJoinResponseDto.java
  src/main/java/com/sscanner/team/user/service/UserService.java
  src/main/resources/application.yml
Labels: ✨ Feature, 지은

#13 Feature/6 board create API
  build.gradle
  src/main/java/com/sscanner/team/Board.java
  src/main/java/com/sscanner/team/BoardImg.java
  src/main/java/com/sscanner/team/board/controller/BoardController.java
  src/main/java/com/sscanner/team/board/entity/Board.java
  src/main/java/com/sscanner/team/board/entity/BoardImg.java
  src/main/java/com/sscanner/team/board/repository/BoardImgRepository.java
  src/main/java/com/sscanner/team/board/repository/BoardRepository.java
  src/main/java/com/sscanner/team/board/requestdto/BoardCreateRequestDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardCreateResponseDTO.java
  src/main/java/com/sscanner/team/board/responsedto/BoardImgCreateResponseDTO.java
  src/main/java/com/sscanner/team/board/service/BoardImgService.java
  src/main/java/com/sscanner/team/board/service/BoardImgServiceImpl.java
  src/main/java/com/sscanner/team/board/service/BoardService.java
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.java
  src/main/java/com/sscanner/team/board/type/BoardCategory.java
  src/main/java/com/sscanner/team/comment/entity/Comment.java
  src/main/java/com/sscanner/team/global/common/service/ImageService.java
  src/main/java/com/sscanner/team/global/common/service/ImageServiceImpl.java
  src/main/java/com/sscanner/team/global/configure/S3Config.java
  src/main/java/com/sscanner/team/global/exception/ExceptionCode.java
  src/main/resources/application.yml
Labels: ✨ Feature, 훈일

#16 Feat: 쓰레기통 정보 변경, 삭제 API 구현
  build.gradle
  src/main/java/com/sscanner/team/trashcan/controller/TrashcanApiController.java
  src/main/java/com/sscanner/team/trashcan/entity/Trashcan.java
  src/main/java/com/sscanner/team/trashcan/requestDto/UpdateTrashcanRequestDto.java
  src/main/java/com/sscanner/team/trashcan/service/TrashService.java
  src/main/java/com/sscanner/team/trashcan/service/TrashcanServiceImpl.java
Labels: ✨ Feature, 서진
