Repository prgrms-be-devcourse/NBE1_2_Team03, pull requests merged in 2024-11, with the labels that each got.

#89 Refactor/87 payment point gifticon
  src/main/java/com/sscanner/team/barcode/controller/BarcodeController.java
  src/main/java/com/sscanner/team/barcode/service/BarcodeService.java
  src/main/java/com/sscanner/team/barcode/service/BarcodeServiceImpl.java
  src/main/java/com/sscanner/team/gifticon/controller/GifticonController.java
  src/main/java/com/sscanner/team/gifticon/service/GifticonService.java
  src/main/java/com/sscanner/team/payment/requestdto/PointPaymentRequestDto.java
  src/main/java/com/sscanner/team/payment/service/PaymentServiceImpl.java
  src/main/java/com/sscanner/team/points/controller/PointController.java
  src/main/java/com/sscanner/team/points/dto/requestdto/PointRequestDto.java
  src/main/java/com/sscanner/team/points/service/PointService.java
  src/main/java/com/sscanner/team/points/service/PointServiceImpl.java
Labels: 🔨 Refactor, 정원

#91 Refactor: Board, Admin과 관련된 issue 해결
  src/main/java/com/sscanner/team/admin/controller/AdminController.java
  src/main/java/com/sscanner/team/admin/service/AdminService.java
  src/main/java/com/sscanner/team/admin/service/AdminServiceImpl.java
  src/main/java/com/sscanner/team/board/controller/BoardController.java
  src/main/java/com/sscanner/team/board/repository/BoardRepository.java
  src/main/java/com/sscanner/team/board/responsedto/BoardResponseDTO.java
  src/main/java/com/sscanner/team/board/service/BoardService.java
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.java
  src/main/java/com/sscanner/team/global/common/service/ImageServiceImpl.java
  src/main/java/com/sscanner/team/points/controller/PointController.java
  src/main/java/com/sscanner/team/points/dto/requestdto/PointRequestDto.java
  src/main/java/com/sscanner/team/points/service/PointService.java
  src/main/java/com/sscanner/team/points/service/PointServiceImpl.java
Labels: 🔨 Refactor, 훈일

#93 Feature/92 add sms registered
  src/main/java/com/sscanner/team/auth/controller/ReissueController.java
  src/main/java/com/sscanner/team/auth/jwt/LoginFilter.java
  src/main/java/com/sscanner/team/auth/responsedto/RefreshResponseDto.java
  src/main/java/com/sscanner/team/auth/service/ReissueService.java
  src/main/java/com/sscanner/team/auth/service/ReissueServiceImpl.java
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.java
  src/main/java/com/sscanner/team/sms/controller/SmsController.java
  src/main/java/com/sscanner/team/sms/service/SmsService.java
  src/main/java/com/sscanner/team/sms/service/SmsServiceImpl.java
Labels: ✨ Feature, 지은

#94 Chore/add elk env
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  docker-compose/compose.blue.yml
  docker-compose/compose.green.yml
Labels: 🔨 Refactor, 재희

#101 Feature/99 register userpoint
  src/main/java/com/sscanner/team/global/configure/RedisConfig.java
  src/main/java/com/sscanner/team/points/common/InitialPoint.java
  src/main/java/com/sscanner/team/points/service/PointService.java
  src/main/java/com/sscanner/team/points/service/PointServiceImpl.java
  src/main/java/com/sscanner/team/user/service/UserServiceImpl.java
Labels: ✨ Feature, 정원

#103 Refactor/100 board
  src/main/java/com/sscanner/team/admin/responsedto/AdminEctBoardResponseDTO.java
  src/main/java/com/sscanner/team/admin/responsedto/AdminModifyBoardResponseDTO.java
  src/main/java/com/sscanner/team/board/controller/BoardController.java
  src/main/java/com/sscanner/team/board/responsedto/BoardResponseDTO.java
  src/main/java/com/sscanner/team/board/service/BoardService.java
  src/main/java/com/sscanner/team/board/service/BoardServiceImpl.java
  src/main/java/com/sscanner/team/comment/controller/CommentController.java
  src/main/java/com/sscanner/team/comment/responsedto/CommentResponseDTO.java
  src/main/java/com/sscanner/team/comment/service/CommentService.java
  src/main/java/com/sscanner/team/comment/service/CommentServiceImpl.java
Labels: 🔨 Refactor, 훈일

#107 chore: openapi 환경변수 추가
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  docker-compose/compose.blue.yml
  docker-compose/compose.green.yml
Labels: 🔨 Refactor, 재희

#106 feature: OpenAI API
  src/main/java/com/sscanner/team/chatbot/controller/OpenAIController.java
  src/main/java/com/sscanner/team/chatbot/service/OpenAIService.java
  src/main/java/com/sscanner/team/global/configure/RestTemplateConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature, 정원

#109 Docs: ReadMe 작성
  README.md
Labels: 📃 Docs, 훈일

#111 Refactor/110 directory
  src/main/java/com/sscanner/team/auth/jwt/JWTFilter.java
  src/main/java/com/sscanner/team/auth/service/CustomUserDetailsService.java
  src/main/java/com/sscanner/team/auth/service/UserDetailsImpl.java
  src/main/java/com/sscanner/team/global/configure/SecurityConfig.java
Labels: 🔨 Refactor, 지은
